name: rusty-roads

services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 6500:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - route-manager

  backend:
    container_name: rusty-roads
    image: rusty-roads:latest
    build:
      context: .
      target: final
      args:
        DATABASE_URL_DOCKER: ${DATABASE_URL_DOCKER}
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    restart: always
    networks:
      - route-manager

volumes:
  pgdata: {}

networks:
  route-manager:
    external: true
